function tafeltrainer3(){var S='bootstrap',T='begin',U='gwt.codesvr.tafeltrainer3=',V='gwt.codesvr=',W='tafeltrainer3',X='startup',Y='DUMMY',Z=0,$=1,_='iframe',ab='javascript:""',bb='position:absolute; width:0; height:0; border:none; left: -1000px;',cb=' top: -1000px;',db='CSS1Compat',eb='<!doctype html>',fb='',gb='<html><head><\/head><body><\/body><\/html>',hb='undefined',ib='DOMContentLoaded',jb=50,kb='Chrome',lb='eval("',mb='");',nb='script',ob='javascript',pb='moduleStartup',qb='moduleRequested',rb='Failed to load ',sb='head',tb='meta',ub='name',vb='tafeltrainer3::',wb='::',xb='gwt:property',yb='content',zb='=',Ab='gwt:onPropertyErrorFn',Bb='Bad handler "',Cb='" for "gwt:onPropertyErrorFn"',Db='gwt:onLoadErrorFn',Eb='" for "gwt:onLoadErrorFn"',Fb='#',Gb='?',Hb='/',Ib='img',Jb='clear.cache.gif',Kb='baseUrl',Lb='tafeltrainer3.nocache.js',Mb='base',Nb='//',Ob='formfactor',Pb='&',Qb='iphone',Rb='ipod',Sb='mobile',Tb='ipad',Ub='tablet',Vb='android',Wb=160,Xb=6,Yb='desktop',Zb=2,$b='user.agent',_b='webkit',ac='safari',bc='msie',cc=10,dc=11,ec='ie10',fc=9,gc='ie9',hc=8,ic='ie8',jc='gecko',kc='gecko1_8',lc=3,mc=4,nc='selectingPermutation',oc='tafeltrainer3.devmode.js',pc='25EB5A84101775974C3E3F0E05C5C399',qc=':1',rc=':2',sc='3377075FF1C6CAC9574CAA26A230269F',tc='62D4AB37D97F3E46D96FB8C786C9467B',uc='7199A9DBAC887ACDC50FFE86571A9B59',vc='DC8B4CB6DD783769D79FDEB8A904546D',wc=':',xc='.cache.js',yc='loadExternalRefs',zc='end',Ac='http:',Bc='file:',Cc='_gwt_dummy_',Dc='__gwtDevModeHook:tafeltrainer3',Ec='Ignoring non-whitelisted Dev Mode URL: ',Fc=':moduleBase';var s=window;var t=document;v(S,T);function u(){var a=s.location.search;return a.indexOf(U)!=-1||a.indexOf(V)!=-1}
function v(a,b){if(s.__gwtStatsEvent){s.__gwtStatsEvent({moduleName:W,sessionId:s.__gwtStatsSessionId,subSystem:X,evtGroup:a,millis:(new Date).getTime(),type:b})}}
tafeltrainer3.__sendStats=v;tafeltrainer3.__moduleName=W;tafeltrainer3.__errFn=null;tafeltrainer3.__moduleBase=Y;tafeltrainer3.__softPermutationId=Z;tafeltrainer3.__computePropValue=null;tafeltrainer3.__getPropMap=null;tafeltrainer3.__installRunAsyncCode=function(){};tafeltrainer3.__gwtStartLoadingFragment=function(){return null};tafeltrainer3.__gwt_isKnownPropertyValue=function(){return false};tafeltrainer3.__gwt_getMetaProperty=function(){return null};var w=null;var A=s.__gwt_activeModules=s.__gwt_activeModules||{};A[W]={moduleName:W};tafeltrainer3.__moduleStartupDone=function(e){var f=A[W].bindings;A[W].bindings=function(){var a=f?f():{};var b=e[tafeltrainer3.__softPermutationId];for(var c=Z;c<b.length;c++){var d=b[c];a[d[Z]]=d[$]}return a}};var B;function C(){D();return B}
function D(){if(B){return}var a=t.createElement(_);a.src=ab;a.id=W;a.style.cssText=bb+cb;a.tabIndex=-1;t.body.appendChild(a);B=a.contentDocument;if(!B){B=a.contentWindow.document}B.open();var b=document.compatMode==db?eb:fb;B.write(b+gb);B.close()}
function F(k){function l(a){function b(){if(typeof t.readyState==hb){return typeof t.body!=hb&&t.body!=null}return /loaded|complete/.test(t.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(t.removeEventListener){t.removeEventListener(ib,d,false)}if(e){clearInterval(e)}}}
if(t.addEventListener){t.addEventListener(ib,d,false)}var e=setInterval(function(){if(b()){d()}},jb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=e.body;var g;if(navigator.userAgent.indexOf(kb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(lb));for(var i=Z;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring($,j.length-$)))}h.appendChild(e.createTextNode(mb));g=e.createElement(nb);g.language=ob;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=Z;i<c.length;i++){g=e.createElement(nb);g.language=ob;g.text=c[i];f.appendChild(g);d(f,g)}}}
tafeltrainer3.onScriptDownloaded=function(a){l(function(){m(a)})};v(pb,qb);var n=t.createElement(nb);n.src=k;if(tafeltrainer3.__errFn){n.onerror=function(){tafeltrainer3.__errFn(W,new Error(rb+code))}}t.getElementsByTagName(sb)[Z].appendChild(n)}
tafeltrainer3.__startLoadingFragment=function(a){return I(a)};tafeltrainer3.__installRunAsyncCode=function(a){var b=C();var c=b.body;var d=b.createElement(nb);d.language=ob;d.text=a;c.appendChild(d);c.removeChild(d)};function G(){var c={};var d;var e;var f=t.getElementsByTagName(tb);for(var g=Z,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ub),k;if(j){j=j.replace(vb,fb);if(j.indexOf(wb)>=Z){continue}if(j==xb){k=i.getAttribute(yb);if(k){var l,m=k.indexOf(zb);if(m>=Z){j=k.substring(Z,m);l=k.substring(m+$)}else{j=k;l=fb}c[j]=l}}else if(j==Ab){k=i.getAttribute(yb);if(k){try{d=eval(k)}catch(a){alert(Bb+k+Cb)}}}else if(j==Db){k=i.getAttribute(yb);if(k){try{e=eval(k)}catch(a){alert(Bb+k+Eb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};w=d;tafeltrainer3.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Fb);if(b==-1){b=a.length}var c=a.indexOf(Gb);if(c==-1){c=a.length}var d=a.lastIndexOf(Hb,Math.min(c,b));return d>=Z?a.substring(Z,d+$):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=t.createElement(Ib);b.src=a+Jb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Kb);if(a!=null){return a}return fb}
function h(){var a=t.getElementsByTagName(nb);for(var b=Z;b<a.length;++b){if(a[b].src.indexOf(Lb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=t.getElementsByTagName(Mb);if(a.length>Z){return a[a.length-$].href}return fb}
function j(){var a=t.location;return a.href==a.protocol+Nb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(t.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return tafeltrainer3.__moduleBase+a}
function J(){var k=[];var l=Z;function m(a,b){var c=k;for(var d=Z,e=a.length-$;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var n=[];var o=[];function p(a){var b=o[a](),c=n[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(w){w(a,d,b)}throw null}
o[Ob]=function(){var a=location.search;var b=a.indexOf(Ob);if(b>=Z){var c=a.substring(b);var d=c.indexOf(zb)+$;var e=c.indexOf(Pb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Qb)!=-1||f.indexOf(Rb)!=-1){return Sb}else if(f.indexOf(Tb)!=-1){return Ub}else if(f.indexOf(Vb)!=-1||f.indexOf(Sb)!=-1){var g=Wb;var h=s.screen.width/g;var i=s.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<Xb?Sb:Ub}return Yb};n[Ob]={desktop:Z,mobile:$,tablet:Zb};o[$b]=function(){var a=navigator.userAgent.toLowerCase();var b=t.documentMode;if(function(){return a.indexOf(_b)!=-1}())return ac;if(function(){return a.indexOf(bc)!=-1&&(b>=cc&&b<dc)}())return ec;if(function(){return a.indexOf(bc)!=-1&&(b>=fc&&b<dc)}())return gc;if(function(){return a.indexOf(bc)!=-1&&(b>=hc&&b<dc)}())return ic;if(function(){return a.indexOf(jc)!=-1||b>=dc}())return kc;return fb};n[$b]={gecko1_8:Z,ie10:$,ie8:Zb,ie9:lc,safari:mc};__gwt_isKnownPropertyValue=function(a,b){return b in n[a]};tafeltrainer3.__getPropMap=function(){var a={};for(var b in n){if(n.hasOwnProperty(b)){a[b]=p(b)}}return a};tafeltrainer3.__computePropValue=p;s.__gwt_activeModules[W].bindings=tafeltrainer3.__getPropMap;v(S,nc);if(u()){return I(oc)}var q;try{m([Yb,gc],pc);m([Sb,gc],pc+qc);m([Ub,gc],pc+rc);m([Yb,ec],sc);m([Sb,ec],sc+qc);m([Ub,ec],sc+rc);m([Yb,kc],tc);m([Sb,kc],tc+qc);m([Ub,kc],tc+rc);m([Yb,ic],uc);m([Sb,ic],uc+qc);m([Ub,ic],uc+rc);m([Yb,ac],vc);m([Sb,ac],vc+qc);m([Ub,ac],vc+rc);q=k[p(Ob)][p($b)];var r=q.indexOf(wc);if(r!=-1){l=parseInt(q.substring(r+$),cc);q=q.substring(Z,r)}}catch(a){}tafeltrainer3.__softPermutationId=l;return I(q+xc)}
function K(){if(!s.__gwt_stylesLoaded){s.__gwt_stylesLoaded={}}v(yc,T);v(yc,zc)}
G();tafeltrainer3.__moduleBase=H();A[W].moduleBase=tafeltrainer3.__moduleBase;var L=J();if(s){var M=!!(s.location.protocol==Ac||s.location.protocol==Bc);s.__gwt_activeModules[W].canRedirect=M;function N(){var b=Cc;try{s.sessionStorage.setItem(b,b);s.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(M&&N()){var O=Dc;var P=s.sessionStorage[O];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(P)){if(P&&(window.console&&console.log)){console.log(Ec+P)}P=fb}if(P&&!s[O]){s[O]=true;s[O+Fc]=H();var Q=t.createElement(nb);Q.src=P;var R=t.getElementsByTagName(sb)[Z];R.insertBefore(Q,R.firstElementChild||R.children[Z]);return false}}}K();v(S,zc);F(L);return true}
tafeltrainer3.succeeded=tafeltrainer3();